name: ray_rllib_agent

dependencies:
  - python=3.7.3
  - pip=19.0.3
  - pip:
    - -e ../../
    - requests==2.21.0  # Needed till https://github.com/ray-project/ray/issues/8373 fixed.
    - tensorflow==2.2.0
    - ray[rllib]==0.8.5
